// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyService.proto

package com.wclsolution.docpal.grpc.example;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wclsolution.docpal.grpc.example.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
