server:
  port: 8600
  servlet:
    context-path: /
spring:
  application:
    name: student-rpc-client
grpc:
  client:
    student-rpc-server:   #服务名称不能写错，这个需要和server端spring.application.name的定义的名称一致，否默认的negotiationType:tls
      address: 'static://localhost:10005'
      # 是否开启保持连接（长连接）
      enableKeepAlive: true
      # 保持连接时长（默认20s）
      keepAliveTimeout: 20s
      # 没有RPC调用时是否保持连接（默认false，可禁用避免额外消耗CPU）
      keepAliveWithoutCalls: false
      # 客户端负载均衡策略(round_robin（默认）, pick_first)
      defaultLoadBalancingPolicy: round_robin
      # 通信类型
      # plaintext | plaintext_upgrade | tls
      # 明文通信且http/2 | 明文通信且升级http/1.1为http/2 | 使用TLS（ALPN/NPN）通信
      negotiationType: plaintext
      max-inbound-message-size: 9155241000
      package-max-inbound-message-size: 9155241000
      server:
        max-inbound-message-size: 9155241000
#    GLOBAL: 可以指定所有grpc通用配置